[package]
name = "circom-groth16-verifier"
version = "0.1.0"
edition = "2021"
publish = false

[lib]
crate-type = ["lib", "cdylib"]
doctest = false

[dependencies]
contract-types = { workspace = true }
soroban-sdk = { workspace = true, features = ["alloc"] }

[build-dependencies]

[dev-dependencies]
ark-bn254 = { workspace = true }
ark-ff = { workspace = true }
ark-groth16 = { workspace = true }
ark-relations = { workspace = true }
ark-std = { workspace = true }
soroban-sdk = { workspace = true, features = ["testutils"] }
soroban-utils = { workspace = true }